In [6]:
from io import StringIO

import pandas as pd
import requests

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

URL = "https://en.wikipedia.org/wiki/List_of_current_NHL_captains_and_alternate_captains"

response = requests.get(URL, headers=HEADERS)
response.raise_for_status()

tables = pd.read_html(StringIO(response.text))

print(f"{len(tables)} tables found")

11 tables found

In [7]:
for i, table in enumerate(tables):

    print("=" * 80)
    print(f"TABLE {i}")

    if isinstance(table.columns, pd.MultiIndex):
        table.columns = [
            c[0] if c[0] == c[1] else "_".join(str(x) for x in c if x)
            for c in table.columns
        ]

    print(table.columns.tolist())
    print(f"{len(table)} rows")

================================================================================
TABLE 0
['Abbreviation', 'Definition']
4 rows
================================================================================
TABLE 1
['Team', 'Captain', 'Since', 'Pos']
34 rows
================================================================================
TABLE 2
['Team', 'Alternate captain(s)', 'Since', 'Pos']
112 rows
================================================================================
TABLE 3
['vteNational Hockey League', 'vteNational Hockey League.1', 'Unnamed: 2', 'Unnamed: 3']
44 rows
================================================================================
TABLE 4
['Western Conference', 'Western Conference.1', 'Eastern Conference', 'Eastern Conference.1']
37 rows
================================================================================
TABLE 5
['Pacific Division', 'Pacific Division.1']
8 rows
================================================================================
TABLE 6
['Central Division', 'Central Division.1']
8 rows
================================================================================
TABLE 7
['Atlantic Division', 'Atlantic Division.1']
8 rows
================================================================================
TABLE 8
['Metropolitan Division', 'Metropolitan Division.1']
8 rows
================================================================================
TABLE 9
[0, 1]
4 rows
================================================================================
TABLE 10
['vteNational Hockey League-related lists and topics', 'vteNational Hockey League-related lists and topics.1']
5 rows

In [8]:
captains = tables[1].copy()

captains.columns = [
    c[0] if isinstance(c, tuple) else c
    for c in captains.columns
]

captains

                     Team              Captain        Since   Pos
0           Anaheim Ducks               Vacant   2026–27[a]  —N/a
1           Boston Bruins               Vacant   2024–25[b]  —N/a
2          Buffalo Sabres       Rasmus Dahlin†  2024–25[10]     D
3                     NaN                  NaN          NaN   NaN
4          Calgary Flames     Mikael Backlund†  2023–24[11]     C
5     Carolina Hurricanes         Jordan Staal  2019–20[12]     C
6      Chicago Blackhawks               Vacant   2025–26[c]  —N/a
7      Colorado Avalanche   Gabriel Landeskog†  2012–13[13]    LW
8   Columbus Blue Jackets               Vacant   2026–27[d]  —N/a
9            Dallas Stars          Jamie Benn†  2013–14[14]    LW
10      Detroit Red Wings        Dylan Larkin†  2020–21[15]     C
11        Edmonton Oilers      Connor McDavid†   2016–17[7]     C
12       Florida Panthers   Aleksander Barkov†  2018–19[16]     C
13      Los Angeles Kings               Vacant   2026–27[e]  —N/a
14         Minnesota Wild      Jared Spurgeon†  2020–21[17]     D
15     Montreal Canadiens         Nick Suzuki†  2022–23[18]     C
16    Nashville Predators          Roman Josi†  2017–18[19]     D
17      New Jersey Devils       Nico Hischier†  2020–21[20]     C
18     New York Islanders               Vacant   2026–27[f]  —N/a
19       New York Rangers         J. T. Miller  2025–26[21]     C
20        Ottawa Senators               Vacant   2026–27[g]  —N/a
21    Philadelphia Flyers      Sean Couturier†  2023–24[22]     C
22    Pittsburgh Penguins       Sidney Crosby†  2007–08[23]     C
23        San Jose Sharks               Vacant   2025–26[h]  —N/a
24         Seattle Kraken        Jordan Eberle  2024–25[24]    RW
25        St. Louis Blues               Vacant   2025–26[i]  —N/a
26    Tampa Bay Lightning       Victor Hedman†  2024–25[25]     D
27                    NaN                  NaN          NaN   NaN
28    Toronto Maple Leafs     Auston Matthews†  2024–25[26]     C
29           Utah Mammoth       Clayton Keller  2024–25[27]    LW
30      Vancouver Canucks               Vacant   2025–26[j]  —N/a
31   Vegas Golden Knights           Mark Stone  2020–21[28]    RW
32    Washington Capitals  Alexander Ovechkin†  2009–10[29]    LW
33          Winnipeg Jets          Adam Lowry†  2023–24[30]     C

In [9]:
alternates = tables[2].copy()

alternates.columns = [
    c[0] if isinstance(c, tuple) else c
    for c in alternates.columns
]

alternates

                    Team Alternate captain(s)    Since  Pos
0          Anaheim Ducks        Leo Carlsson†  2025–26    C
1          Anaheim Ducks     Jackson LaCombe†  2025–26    D
2          Anaheim Ducks         Alex Killorn  2023–24   LW
3          Boston Bruins                  NaN      NaN  NaN
4          Boston Bruins      Hampus Lindholm  2025–26    D
..                   ...                  ...      ...  ...
107  Washington Capitals          Tom Wilson†  2023–24   RW
108        Winnipeg Jets                  NaN      NaN  NaN
109        Winnipeg Jets      Josh Morrissey†  2019–20    D
110        Winnipeg Jets      Mark Scheifele†  2016–17    C
111        Winnipeg Jets                  NaN      NaN  NaN

[112 rows x 4 columns]

In [10]:
pd.set_option("display.max_rows", 150)
pd.set_option("display.max_columns", None)

alternates

                      Team  Alternate captain(s)        Since  Pos
0            Anaheim Ducks         Leo Carlsson†      2025–26    C
1            Anaheim Ducks      Jackson LaCombe†      2025–26    D
2            Anaheim Ducks          Alex Killorn      2023–24   LW
3            Boston Bruins                   NaN          NaN  NaN
4            Boston Bruins       Hampus Lindholm      2025–26    D
5            Boston Bruins                   NaN          NaN  NaN
6            Boston Bruins       Charlie McAvoy†  2023–24[31]    D
7          David Pastrnak†           2023–24[31]           RW  NaN
8           Buffalo Sabres                   NaN          NaN  NaN
9           Buffalo Sabres   Mattias Samuelsson†      2024–25    D
10          Buffalo Sabres         Tage Thompson      2024–25    C
11          Calgary Flames                   NaN          NaN  NaN
12          Calgary Flames                   NaN          NaN  NaN
13          Calgary Flames    Jonathan Huberdeau  2022–23[32]   LW
14                  Vacant               2026–27            –  NaN
15     Carolina Hurricanes                   NaN          NaN  NaN
16     Carolina Hurricanes        Sebastian Aho†      2021–22    C
17     Carolina Hurricanes      Jordan Martinook  2019–20[33]   LW
18     Carolina Hurricanes        Jaccob Slavin†  2019–20[34]    D
19      Chicago Blackhawks                   NaN          NaN  NaN
20      Chicago Blackhawks        Connor Bedard†      2025–26    C
21      Chicago Blackhawks        Tyler Bertuzzi      2025–26   LW
22      Colorado Avalanche                   NaN          NaN  NaN
23      Colorado Avalanche     Nathan MacKinnon†      2016–17    C
24      Colorado Avalanche           Cale Makar†      2023–24    D
25   Columbus Blue Jackets                   NaN          NaN  NaN
26   Columbus Blue Jackets       Erik Gudbranson      2023–24    D
27   Columbus Blue Jackets        Zach Werenski†  2021–22[35]    D
28            Dallas Stars                   NaN          NaN  NaN
29            Dallas Stars       Miro Heiskanen†      2022–23    D
30            Dallas Stars          Roope Hintz†      2024–25    C
31            Dallas Stars          Esa Lindell†      2019–20    D
32            Dallas Stars          Tyler Seguin      2017–18    C
33       Detroit Red Wings                   NaN          NaN  NaN
34       Detroit Red Wings        Lucas Raymond†      2025–26   RW
35       Detroit Red Wings        Moritz Seider†      2025–26    D
36         Edmonton Oilers                   NaN          NaN  NaN
37         Edmonton Oilers       Leon Draisaitl†  2019–20[36]    C
38         Edmonton Oilers  Ryan Nugent-Hopkins†  2015–16[37]    C
39        Florida Panthers                   NaN          NaN  NaN
40        Florida Panthers         Aaron Ekblad†      2016–17    D
41        Florida Panthers       Matthew Tkachuk      2022–23   RW
42                     NaN                   NaN          NaN  NaN
43       Los Angeles Kings       Mikey Anderson†      2025–26    D
44       Los Angeles Kings         Drew Doughty†      2016–17    D
45       Los Angeles Kings         Adrian Kempe†      2025–26   RW
46          Minnesota Wild        Marcus Foligno      2021–22   LW
47          Minnesota Wild      Kirill Kaprizov†      2023–24   LW
48      Montreal Canadiens         Mike Matheson  2023–24[38]    D
49      Montreal Canadiens                Vacant      2026–27    —
50                     NaN                   NaN          NaN  NaN
51     Nashville Predators                   NaN          NaN  NaN
52     Nashville Predators                   NaN          NaN  NaN
53     Nashville Predators       Filip Forsberg†      2024–25   LW
54     Nashville Predators         Ryan O'Reilly      2023–24    C
55          Steven Stamkos               2025–26            C  NaN
56       New Jersey Devils                   NaN          NaN  NaN
57       New Jersey Devils         Jesper Bratt†      2025–26   LW
58       New Jersey Devils          Jack Hughes†      2022–23    C
59      New York Islanders                   NaN          NaN  NaN
60      New York Islanders             Bo Horvat      2024–25    C
61      New York Islanders         Kyle Palmieri  2024–25[39]   RW
62      New York Islanders                   NaN          NaN  NaN
63            Ryan Pulock†               2024–25            D  NaN
64        New York Rangers                   NaN          NaN  NaN
65        New York Rangers             Adam Fox†      2023–24    D
66        New York Rangers        Mika Zibanejad      2018-19    C
67         Ottawa Senators                   NaN          NaN  NaN
68         Ottawa Senators        Thomas Chabot†      2019–20    D
69         Ottawa Senators         Claude Giroux      2022–23   RW
70     Philadelphia Flyers                   NaN          NaN  NaN
71     Philadelphia Flyers       Travis Konecny†  2023–24[40]   RW
72     Philadelphia Flyers       Travis Sanheim†      2025–26    D
73     Pittsburgh Penguins          Kris Letang†      2017–18    D
74     Pittsburgh Penguins        Evgeni Malkin†      2008–09    C
75                     NaN                   NaN          NaN  NaN
76         San Jose Sharks                   NaN          NaN  NaN
77         San Jose Sharks    Macklin Celebrini†  2025–26[41]    C
78         San Jose Sharks                   NaN          NaN  NaN
79         San Jose Sharks       Barclay Goodrow      2024–25    C
80         San Jose Sharks         Tyler Toffoli      2024–25   RW
81      Alexander Wennberg               2025–26            C  NaN
82                     NaN                   NaN          NaN  NaN
83          Seattle Kraken        Matty Beniers†      2024–25    C
84          Seattle Kraken          Adam Larsson      2021–22    D
85         St. Louis Blues                   NaN          NaN  NaN
86         St. Louis Blues      Jake Neighbours†      2025–26   LW
87         St. Louis Blues       Colton Parayko†      2020–21    D
88         St. Louis Blues        Robert Thomas†  2023–24[42]    C
89     Tampa Bay Lightning                   NaN          NaN  NaN
90     Tampa Bay Lightning      Nikita Kucherov†      2022–23   RW
91     Tampa Bay Lightning         Ryan McDonagh      2024–25    D
92                     NaN                   NaN          NaN  NaN
93     Toronto Maple Leafs        Morgan Rielly†      2016–17    D
94     Toronto Maple Leafs          John Tavares  2024–25[26]    C
95            Utah Mammoth         Lawson Crouse      2024–25   LW
96            Utah Mammoth     Mikhail Sergachev      2024–25    D
97                     NaN                   NaN          NaN  NaN
98       Vancouver Canucks         Brock Boeser†      2025–26   RW
99       Vancouver Canucks          Filip Hronek      2025–26    D
100      Vancouver Canucks     Elias Pettersson†      2022–23    C
101   Vegas Golden Knights                   NaN          NaN  NaN
102   Vegas Golden Knights           Jack Eichel      2023–24    C
103   Vegas Golden Knights      William Karlsson      2023–24    C
104   Vegas Golden Knights      Alex Pietrangelo      2020–21    D
105                    NaN                   NaN          NaN  NaN
106    Washington Capitals          Dylan Strome      2025–26    C
107    Washington Capitals           Tom Wilson†      2023–24   RW
108          Winnipeg Jets                   NaN          NaN  NaN
109          Winnipeg Jets       Josh Morrissey†      2019–20    D
110          Winnipeg Jets       Mark Scheifele†      2016–17    C
111          Winnipeg Jets                   NaN          NaN  NaN

In [11]:
from bs4 import BeautifulSoup
import requests

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

URL = "https://en.wikipedia.org/wiki/List_of_current_NHL_captains_and_alternate_captains"

html = requests.get(URL, headers=HEADERS).text

soup = BeautifulSoup(html, "html.parser")

print("Downloaded")

Downloaded

In [12]:
tables = soup.find_all("table", class_="wikitable")

print(len(tables))

for i, table in enumerate(tables):
    print("=" * 80)
    print(i)
    print(table.find("caption").get_text(strip=True))

3
================================================================================
0
Position abbreviations
================================================================================
1
List of current NHL Captains
================================================================================
2
List of current NHL alternate captains

In [14]:
alternate_table = tables[2]

rows = alternate_table.find_all("tr")

print(f"{len(rows)} rows")

for i, row in enumerate(rows[:20]):

    cells = row.find_all(["th", "td"])

    print("=" * 80)
    print(f"Row {i} ({len(cells)} cells)")
    print([c.get_text(" ", strip=True) for c in cells])

112 rows
================================================================================
Row 0 (4 cells)
['Team', 'Alternate captain(s)', 'Since', 'Pos']
================================================================================
Row 1 (4 cells)
['Anaheim Ducks', 'Leo Carlsson †', '2025–26', 'C']
================================================================================
Row 2 (3 cells)
['Jackson LaCombe †', '2025–26', 'D']
================================================================================
Row 3 (3 cells)
['Alex Killorn', '2023–24', 'LW']
================================================================================
Row 4 (1 cells)
['Boston Bruins']
================================================================================
Row 5 (3 cells)
['Hampus Lindholm', '2025–26', 'D']
================================================================================
Row 6 (0 cells)
[]
================================================================================
Row 7 (3 cells)
['Charlie McAvoy †', '2023–24 [ 31 ]', 'D']
================================================================================
Row 8 (3 cells)
['David Pastrnak †', '2023–24 [ 31 ]', 'RW']
================================================================================
Row 9 (1 cells)
['Buffalo Sabres']
================================================================================
Row 10 (3 cells)
['Mattias Samuelsson †', '2024–25', 'D']
================================================================================
Row 11 (3 cells)
['Tage Thompson', '2024–25', 'C']
================================================================================
Row 12 (1 cells)
['Calgary Flames']
================================================================================
Row 13 (0 cells)
[]
================================================================================
Row 14 (3 cells)
['Jonathan Huberdeau', '2022–23 [ 32 ]', 'LW']
================================================================================
Row 15 (3 cells)
['Vacant', '2026–27', '–']
================================================================================
Row 16 (1 cells)
['Carolina Hurricanes']
================================================================================
Row 17 (3 cells)
['Sebastian Aho †', '2021–22', 'C']
================================================================================
Row 18 (3 cells)
['Jordan Martinook', '2019–20 [ 33 ]', 'LW']
================================================================================
Row 19 (3 cells)
['Jaccob Slavin †', '2019–20 [ 34 ]', 'D']

In [17]:
import pandas as pd

records = []

current_team = None
current_alternates = []

rows = alternate_table.find_all("tr")

for row in rows[1:]:      # Skip header

    cells = row.find_all(["td", "th"])

    texts = [
        clean_text(c.get_text(" ", strip=True))
        for c in cells
    ]

    # Ignore blank rows
    if len(texts) == 0:
        continue

    # First team in the table
    if len(texts) == 4:

        if current_team is not None:

            records.append({
                "Team": current_team,
                "Alternates": current_alternates.copy()
            })

        current_team = texts[0]
        current_alternates = [texts[1]]

    # New team heading
    elif len(texts) == 1:

        if current_team is not None:

            records.append({
                "Team": current_team,
                "Alternates": current_alternates.copy()
            })

        current_team = texts[0]
        current_alternates = []

    # Additional alternate captain
    elif len(texts) == 3:

        current_alternates.append(texts[0])

# Last team
records.append({
    "Team": current_team,
    "Alternates": current_alternates.copy()
})

alternate_parsed = pd.DataFrame(records)

alternate_parsed

                     Team                                         Alternates
0           Anaheim Ducks      [Leo Carlsson, Jackson LaCombe, Alex Killorn]
1           Boston Bruins  [Hampus Lindholm, Charlie McAvoy, David Pastrnak]
2          Buffalo Sabres                [Mattias Samuelsson, Tage Thompson]
3          Calgary Flames                       [Jonathan Huberdeau, Vacant]
4     Carolina Hurricanes   [Sebastian Aho, Jordan Martinook, Jaccob Slavin]
5      Chicago Blackhawks                    [Connor Bedard, Tyler Bertuzzi]
6      Colorado Avalanche                     [Nathan MacKinnon, Cale Makar]
7   Columbus Blue Jackets                   [Erik Gudbranson, Zach Werenski]
8            Dallas Stars  [Miro Heiskanen, Roope Hintz, Esa Lindell, Tyl...
9       Detroit Red Wings                     [Lucas Raymond, Moritz Seider]
10        Edmonton Oilers              [Leon Draisaitl, Ryan Nugent-Hopkins]
11       Florida Panthers                    [Aaron Ekblad, Matthew Tkachuk]
12      Los Angeles Kings       [Mikey Anderson, Drew Doughty, Adrian Kempe]
13         Minnesota Wild                  [Marcus Foligno, Kirill Kaprizov]
14     Montreal Canadiens                            [Mike Matheson, Vacant]
15    Nashville Predators    [Filip Forsberg, Ryan O'Reilly, Steven Stamkos]
16      New Jersey Devils                        [Jesper Bratt, Jack Hughes]
17     New York Islanders            [Bo Horvat, Kyle Palmieri, Ryan Pulock]
18       New York Rangers                         [Adam Fox, Mika Zibanejad]
19        Ottawa Senators                     [Thomas Chabot, Claude Giroux]
20    Philadelphia Flyers                   [Travis Konecny, Travis Sanheim]
21    Pittsburgh Penguins                       [Kris Letang, Evgeni Malkin]
22        San Jose Sharks  [Macklin Celebrini, Barclay Goodrow, Tyler Tof...
23         Seattle Kraken                      [Matty Beniers, Adam Larsson]
24        St. Louis Blues   [Jake Neighbours, Colton Parayko, Robert Thomas]
25    Tampa Bay Lightning                   [Nikita Kucherov, Ryan McDonagh]
26    Toronto Maple Leafs                      [Morgan Rielly, John Tavares]
27           Utah Mammoth                 [Lawson Crouse, Mikhail Sergachev]
28      Vancouver Canucks     [Brock Boeser, Filip Hronek, Elias Pettersson]
29   Vegas Golden Knights  [Jack Eichel, William Karlsson, Alex Pietrangelo]
30    Washington Capitals                         [Dylan Strome, Tom Wilson]
31          Winnipeg Jets                   [Josh Morrissey, Mark Scheifele]

In [16]:
import re

def clean_text(value):

    if value is None:
        return None

    value = str(value)

    # Remove Wikipedia reference numbers
    value = re.sub(r"\[\s*\d+\s*\]", "", value)

    # Remove dagger symbols
    value = value.replace("†", "")

    # Normalise whitespace
    value = " ".join(value.split())

    return value.strip()